#!/bin/bash 
#SBATCH -J myGPU           # job name 
#SBATCH -o myGPU%j       # output and error file name (%j expands to jobID) 
#SBATCH -n 16              # total number of mpi tasks requested 
#SBATCH -p normal     # queue (partition) -- normal, development, etc. 
#SBATCH -t 00:10:00        # run time (hh:mm:ss) - 5 minutes 
#SBATCH -A EE-382C-EE361C-Multi 
#SBATCH --mail-user=user@ece.utexas.edu # replace by your email 
#SBATCH --mail-type=begin  # email me when the job starts 
#SBATCH --mail-type=end    # email me when the job finishes 
java benchMarking/ThroughPut 17
